// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTTYKPH.Data;

#nullable disable

namespace QLTTYKPH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTTYKPH.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Khảo sát môn học"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khảo sát cơ sở vật chất"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khảo sát dịch vụ sinh viên"
                        });
                });

            modelBuilder.Entity("QLTTYKPH.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phòng Đào tạo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phòng Khảo thí"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phòng Quản trị"
                        });
                });

            modelBuilder.Entity("QLTTYKPH.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("QLTTYKPH.Models.FeedbackAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("QuestionId");

                    b.ToTable("FeedbackAnswers");
                });

            modelBuilder.Entity("QLTTYKPH.Models.ProcessingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("HandlerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("HandlerUserId");

                    b.ToTable("ProcessingRecords");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ClassTarget")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("QLTTYKPH.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên",
                            Password = "$2a$11$nlXS4cp2ZZhXZRI50rfkeea/aYieEeIhjNrZ2ahbA2G2r1v0OX3pm",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nguyễn Văn A",
                            Password = "$2a$11$4j6q4wBUDFTj.dJ1ihVpsO42eIYsvdSm7fg62Jmcx1UFoQfMZwMhK",
                            Role = 1,
                            Username = "staff01"
                        },
                        new
                        {
                            Id = 3,
                            Class = "CNTT01",
                            FullName = "Trần Thị B",
                            Password = "$2a$11$bHphvEqo9E3O9RQEpscPFe1JUNjbaGYwHHfNmchBRiMkFO5r7Ap5K",
                            Role = 2,
                            Username = "sv001"
                        });
                });

            modelBuilder.Entity("QLTTYKPH.Models.Feedback", b =>
                {
                    b.HasOne("QLTTYKPH.Models.Survey", "Survey")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTTYKPH.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLTTYKPH.Models.FeedbackAnswer", b =>
                {
                    b.HasOne("QLTTYKPH.Models.Feedback", "Feedback")
                        .WithMany("FeedbackAnswers")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTTYKPH.Models.Question", "Question")
                        .WithMany("FeedbackAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QLTTYKPH.Models.ProcessingRecord", b =>
                {
                    b.HasOne("QLTTYKPH.Models.Feedback", "Feedback")
                        .WithMany("ProcessingRecords")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTTYKPH.Models.User", "HandlerUser")
                        .WithMany("ProcessingRecords")
                        .HasForeignKey("HandlerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("HandlerUser");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Question", b =>
                {
                    b.HasOne("QLTTYKPH.Models.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Survey", b =>
                {
                    b.HasOne("QLTTYKPH.Models.Category", "Category")
                        .WithMany("Surveys")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLTTYKPH.Models.Department", "Department")
                        .WithMany("Surveys")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Category", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Department", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Feedback", b =>
                {
                    b.Navigation("FeedbackAnswers");

                    b.Navigation("ProcessingRecords");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Question", b =>
                {
                    b.Navigation("FeedbackAnswers");
                });

            modelBuilder.Entity("QLTTYKPH.Models.Survey", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QLTTYKPH.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ProcessingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
